name: Deploy to IPFS via Pinata

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to IPFS
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1
        with:
          pinata-jwt: ${{ secrets.PINATA_JWT }}
          path: ./public
          verbose: true 

      - name: Output CID
        run: echo "Deployed CID: ${{ steps.deploy.outputs.cid }}"
