name: Deploy to IPFS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to IPFS via Pinata
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.5.2
        with:
          pinata-jwt: ${{ secrets.PINATA_JWT }}
          path: ./public
          verbose: true 
